spring.application.name=notification
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/mobile-notification
spring.datasource.username=mobile-notification
spring.datasource.password=m0b!le-n0t!f!cat!on
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=mobile-notification

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

## producer akan melakukan retry sebanyak 5 kali dengan selang waktu 2 detik
spring.kafka.producer.retries=5
spring.kafka.producer.properties.retry.backoff.ms=2000
## batas waktu maksimal sebelum timeout adalah 2 menit
spring.kafka.producer.properties.delivery.timeout.ms=120000
## lama waktu producer menunggu response dari broker adalah 30 detik untuk kemudian dilakukan retry
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
